### ISSUE TITLE
Unable to download Glue Data

### ISSUE THREAD

**Issue by sandy9999** [Hazelsuko07/TextHide#1]
<https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FCoLA.zip?alt=media&token=46d5e637-3411-4188-bc44-5809b5bfb5f4> gives Permission Denied when I run download_glue_data.py.

**Comment by Hazelsuko07** [comment]
Hi Sandy,

Thanks for the issue! 

I tried and came across the same problem when trying to **download the whole dataset**. I just raised this to the GLUE team.

But I found that the download links **for each dataset** work: https://gluebenchmark.com/tasks. Maybe you can give it a try.

Best

**Comment by Hazelsuko07** [comment]
Hi Sandy,

I haven't heard back from the GLUE team, but I just zipped my own folder for 'glue_data': https://drive.google.com/file/d/13IDXE73vIgArQhQjh9Cib8CX5AHXUw4k/view?usp=sharing.

Please let me know if you have trouble accessing it.

**Comment by sandy9999** [comment]
Thank you so much @Hazelsuko07 ! This works just as well.
