### ISSUE TITLE
TextHide in Question Answering

### ISSUE THREAD

**Issue by sandy9999** [Hazelsuko07/TextHide#3]
I noticed that mixup and masking were applied only to BertForSequenceClassification but not for tasks such as BertForQuestionAnswering. Is there something that I am missing?

**Comment by Hazelsuko07** [comment]
Hi Sandy,

Thanks for your question. Yes, you are correct. As we've mentioned in our paper, TextHide is designed for classification tasks (Fig 1 also suggested this). 

We hope our work motivates applications to other NLP tasks, such as the QA task you've mentioned.

**Comment by sandy9999** [comment]
Thank you for your response. We will work on applications of TextHide to other NLP tasks.
