### ISSUE TITLE
How the FL training is performed

### ISSUE THREAD

**Issue by willowdong** [Hazelsuko07/TextHide#4]
Thanks for open the code! But I'm confused about how the federated learning setting is performed, I found the training function in this code is just normal training process, if I misunderstand, please correct me.

**Comment by Hazelsuko07** [comment]
Hi,

You are correct. The code is demonstrated using a single-client scenario. To simulate a multi-client setting, you may want to create different threads for different clients and apply the TextHide separately for each one of them.

Best,
Yangsibo
